language: c      # на практике разницы между специфичным для C++ окружением
# и, скажем, python -- никакой. Но пусть будет cpp.

os:
  # будем прогонять CI и на Linux, и на Mac OS X...
  - linux
  - osx

compiler:
  # ... и с помощью GCC, и Clang
  - gcc
  - clang

addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - make
      - cmake


env:
  # список переменных окружения, влияющих на матрицу сборки:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
