language: c      # на практике разницы между специфичным для C++ окружением
# и, скажем, python -- никакой. Но пусть будет cpp.

os:
  # будем прогонять CI и на Linux, и на Mac OS X...
  - linux
  - osx

